// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi1.Server.Data;

#nullable disable

namespace WebApi1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230907061945_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorClassLibrary1.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grossery"
                        });
                });

            modelBuilder.Entity("RazorClassLibrary1.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Brand 1",
                            CategoryId = 2,
                            Name = "Product 1",
                            Price = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Brand 2",
                            CategoryId = 2,
                            Name = "Product 2",
                            Price = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Brand 3",
                            CategoryId = 2,
                            Name = "Product 3",
                            Price = 3,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Brand 4",
                            CategoryId = 1,
                            Name = "Product 4",
                            Price = 4,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Brand 5",
                            CategoryId = 1,
                            Name = "Product 5",
                            Price = 5,
                            Quantity = 5
                        });
                });

            modelBuilder.Entity("RazorClassLibrary1.Product", b =>
                {
                    b.HasOne("RazorClassLibrary1.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
